spring.application.name=fake-miner-api

server.port=${SERVER_PORT:8080}
server.tomcat.basedir=./tomcat-temp

management.endpoints.web.exposure.include=health

telegram.bot.habilitado=${TELEGRAM_BOT_HABILITADO:true}
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.bot.username=${TELEGRAM_BOT_USERNAME:}
telegram.bot.chat-id=${TELEGRAM_CHAT_ID:}

fakeminer.coleta.intervalo-ms=5000
fakeminer.resumo.intervalo-ms=3600000
